package com.taku.safe.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.taku.safe.db.bean.NoticeMsg;

import com.taku.safe.db.dao.NoticeMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noticeMsgDaoConfig;

    private final NoticeMsgDao noticeMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noticeMsgDaoConfig = daoConfigMap.get(NoticeMsgDao.class).clone();
        noticeMsgDaoConfig.initIdentityScope(type);

        noticeMsgDao = new NoticeMsgDao(noticeMsgDaoConfig, this);

        registerDao(NoticeMsg.class, noticeMsgDao);
    }
    
    public void clear() {
        noticeMsgDaoConfig.clearIdentityScope();
    }

    public NoticeMsgDao getNoticeMsgDao() {
        return noticeMsgDao;
    }

}
